import DefaultHeadTags from '@/components/DefaultHeadTags/DefaultHeadTags';

export default function Head() {
  return (
    <>
      <title>Chat</title>
      <meta name="description" content="Generated by create next app" />
      <DefaultHeadTags />
    </>
  );
}
